=== prasannayasan/HRMS-Demo-App/employee.dtd
<?xml version="1.0" encoding="UTF-8"?>
      
<!ELEMENT AJG (integration,salesforce)>
<!ELEMENT integration (teamsize,tool,score)>
<!ATTLIST integration lang (java|python|c) "java">
<!ELEMENT teamsize (#PCDATA)>
<!ELEMENT tool (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ATTLIST integration tid ID #REQUIRED>
<!ELEMENT salesforce (teamsize,tool,score)>
<!ATTLIST salesforce tid ID #REQUIRED>
<!ATTLIST salesforce lang (java|python|c) "c">

=== prasannayasan/HRMS-Demo-App/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employee SYSTEM "employee.dtd">
<AJG>
	<integration tid = "A1" lang = "java">
			<teamsize>9</teamsize>
			<tool>adeptia</tool>
			<score>95</score>
	</integration>
	
	<salesforce tid = "B1" lang = "c" >
			<teamsize>9</teamsize>
			<tool>apex</tool>
			<score>50</score>
	</salesforce>
</AJG>
